language: node_js

sudo: required

addons:
  apt:
    packages:
      - clang
      - libudev-dev
      - build-essential

before_install:
  - wget https://github.com/OpenZWave/open-zwave/archive/master.zip
  - unzip master.zip
  - cd open-zwave-master
  - sudo make install
  - npm install -g node-gyp

env:
  global:
    - CC=clang
    - CXX=clang++

node_js:
  - "0.12"
  - "4"
  - "6"

script:
  - node-gyp configure
  - node-gyp build
