language: node_js

sudo: false

addons:
  apt:
    packages:
      - libudev-dev
      - build-essential

before_install:
  - wget http://mirror.my-ho.st/Downloads/OpenZWave/Debian_8.0/amd64/libopenzwave1.3-dev_1.4.164_amd64.deb
  - wget http://mirror.my-ho.st/Downloads/OpenZWave/Debian_8.0/amd64/libopenzwave1.3_1.4.164_amd64.deb
  - sudo dpkg -i libopenzwave*

env:
  global:
    - CC=/usr/bin/gcc
    - CXX=/usr/bin/g++

node_js:
  - "0.12"
  - "4"
  - "6"

script:
  - npm test
