language: node_js

sudo: required

addons:
  apt:
    packages:
      - libudev-dev
      - build-essential

before_install:
  - wget https://github.com/OpenZWave/open-zwave/archive/master.zip
  - unzip master.zip
  - cd open-zwave-master
  - sudo make install

env:
  global:
    - CC=/usr/bin/gcc
    - CXX=/usr/bin/g++

node_js:
  - "0.12"
  - "4"
  - "6"

script:
  - node-gyp configure
  - node-gyp build
