language: node_js

sudo: false

addons:
  apt:
    sources:
      - openzwave

    packages:
      - build-essentials

env:
  global:
    - CC=/usr/bin/gcc
    - CXX=/usr/bin/g++

node_js:
  - "0.12"
  - "4"
  - "6"

script:
  - npm test
